fix verbosity, change other bits

diff --git a/rmvim b/rmvim
--- a/rmvim
+++ b/rmvim
@@ -6,14 +6,17 @@
 #		  however.
 #	"~$"	: tilde at the end of the file name
 
-while getopts "fr" opt; do
+while getopts "frv" opt; do
 	case $opt in
 		f) # force, no prompt
-			no_prompt=true
+			is_force=true
+			is_verbose=true
 			;;
 		r) # recursive
 			is_recursive=true
 			;;
+		v) # verbose
+			is_verbose=true
 	esac			
 done
 
@@ -23,32 +26,29 @@ else
 	tilde_files=`find . -maxdepth 1 -mindepth 1 -type f -regex "\./.+~$"`
 fi
 
-if [[ -z ${tilde_files} ]]; then # if is null (none found)
+if [[ -z "${tilde_files}" ]]; then # if is null (none found)
 	echo "No ~ files found."
 	exit 1
-else
-	for file in ${tilde_files}
-	do
-		if [ ${no_prompt} ]; then
-			rm_err="$(rm -f ${file} 2>&1 1> /dev/null)"
-			if [ $? -eq 0 ]; then
-				echo "${file} removed successfully"
-			else
-				echo "${file} not removed: ${rm_err}"
-			fi
-			continue
-		fi
-		read -n 1 -p "Remove '${file}'? (y/n): " yn
-		if [ "$yn" == "y" ]; then
-			rm -f ${file} 2> /dev/null
-			if [ $? -ne 0 ]; then
-				echo
-				echo -n "rm had an error. Continuing."
-			fi
-		else
-			echo
-			echo -en "Not removing ${file}."
-		fi
-	echo
-	done
 fi
+
+for file in ${tilde_files}; do
+	if [ ! $is_force ]; then
+		read -n 1 -p "Remove '${file}'? (y/n): " yn
+	fi
+
+	if [ $yn == 'y' ] || [ $is_force ]; then
+		rm -f ${file}
+		exit_code=$?
+	fi
+
+	if [ $is_verbose ]; then
+		if [ $yn == 'y' ] || [ $is_force ]; then
+			if [ $exit_code -eq 0 ]; then
+				echo "removed ‘${file}’"
+			else
+				echo "rm had an error: exit code $exit_code"
+			fi
+		fi
+	fi
+	echo
+done
